### ISSUE TITLE
Reimplement using Node

### ISSUE THREAD

**Issue by daltonscharff** [AaronRiegel/Neith#1]
I don't know what this app does, but it should be doing it with JavaScript.

**Comment by daltonscharff** [comment]
Also use VS Code instead of Jetbrains

**Comment by daltonscharff** [comment]
I like the name though.

**Comment by daltonscharff** [comment]
You could say it's pretty Neith

**Comment by AaronRiegel** [comment]
Someday, maybe I will try JS. I will definitely write up a readme though
